services:
  # Development service with hot reload
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5174:5174"
    volumes:
      # Mount source code for hot reload
      - ../src:/app/src
      - ../public:/app/public
      - ../index.html:/app/index.html
      - ../vite.config.ts:/app/vite.config.ts
      - ../tsconfig.json:/app/tsconfig.json
      - ../tsconfig.app.json:/app/tsconfig.app.json
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_ENABLE_PERFORMANCE_MONITORING=true
      - PORT=5174
    command: pnpm dev --host 0.0.0.0 --port 5174
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5174"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production service (nginx)
  app-prod:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    profiles:
      - production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Future services can be added here
  # database:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: myapp
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   profiles:
  #     - fullstack